### ISSUE TITLE
UnboundLocalError when there's no icon attribute

### ISSUE THREAD

**Issue by djrarky** [coach1988/IPTV-Solution#2]
During the process of running  "Download, filter and import upstream playlist(s)", within Upstream - Playlists, the error `Error: local variable 'fk_logo' referenced before assignment` is thrown

Environment:

```
Request Method: POST
Request URL: http://docker02:8088/admin/manager/iptvupstreamplaylist/

Django Version: 4.2.1
Python Version: 3.9.16
Installed Applications:
['manager.apps.ManagerConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1959, in changelist_view
    response = self.response_action(
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1593, in response_action
    response = func(self, request, queryset)
  File "/app/manager/admin.py", line 166, in update_upstream_playlists
    upstream_playlist_helper.import_channels()
  File "/app/lib/upstream_playlist_helper.py", line 131, in import_channels
    iptvChannel.objects.aupdate_or_create(name=name, defaults={'url':url, 'tvg_id':tvg_id, 'tvg_name':tvg_name,'tvg_logo':fk_logo, 'group_title':fk_group}))

Exception Type: UnboundLocalError at /admin/manager/iptvupstreamplaylist/
Exception Value: local variable 'fk_logo' referenced before assignment
```

Within upstream_playlist_helper.py, attempted the following at line 128:

```
if logo != '':
    logger.info(f'UPSTREAM {self.playlist.name}: Importing logo "{logo}"')
    fk_logo, created = iptvIcon.objects.update_or_create(url=logo)
else:
    fk_logo = "

```

and also 

```
if logo != '':
    logger.info(f'UPSTREAM {self.playlist.name}: Importing logo "{logo}"')
    fk_logo, created = iptvIcon.objects.update_or_create(url=logo)
else:
    fk_logo = None

```

However the error unfortunately persists.

**Comment by coach1988** [comment]
@djrarky: I forgot to mention in our chat: Could you please check which channel it is processing and then post the (redacted, please remove any URL) corresponding entry from the original m3u (downloadable via the dropdown menu above the upstream playlist menu)? It should consist of two lines, the first one would be my main concern.
Of course only if the rebuild didn't work;)

**Comment by djrarky** [comment]
I was dumb and hadn't rebuilt the docker container. 

https://github.com/coach1988/IPTV-Solution/pull/3 - resolves this issue.

**Comment by coach1988** [comment]
Perfect, I'll implement it as soon as I'm back=)
Thanks for testing.

PS: I think something is wrong with the automatic EPG refresh at the moment as well, so be ready for multiple changes;)

**Comment by coach1988** [comment]
@djrarky: Sorry for the dealy, but this has been finally implemented, amongst a whole slew of other things=)
